const FilmCardActionTypes = {
  REQUEST_FILM_DATA_START: "REQUEST_FILM_DATA_START",
  REQUEST_FILM_DATA_SUCCESS: "REQUEST_FILM_DATA_SUCCESS",
  REQUEST_FILM_DATA_FAILURE: "REQUEST_FILM_DATA_FAILURE",
};

export default FilmCardActionTypes;
