const FilmCardActionTypes = {
  REQUEST_FILM_DATA_START: "REQUEST_FILM_DATA_START",
  REQUEST_FILM_DATA_SUCCESS: "REQUEST_FILM_DATA_SUCCESS",
  REQUEST_FILM_DATA_FAILED: "REQUEST_FILM_DATA_FAILED",
};

export default FilmCardActionTypes;
